// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#include "pch.h"
#include "Actor.h"
#include "ObjectMacros.h"
#include "LuaBindHelpers.h"

// ===== Class Factory Registration (IMPLEMENT_CLASS) =====

// IMPLEMENT_CLASS(AActor) expansion
namespace {
    struct AActorFactoryRegister
    {
        AActorFactoryRegister()
        {
            ObjectFactory::RegisterClassType(
                AActor::StaticClass(),
                []() -> UObject* { return new AActor(); }
            );
        }
    };
    static AActorFactoryRegister GRegister_AActor;
    static bool bIsRegistered_AActor = [](){ AActor::StaticClass(); return true; }();
}

// Static member initialization for reflection registration
const bool AActor::bPropertiesRegistered = []() {
    AActor::StaticRegisterProperties();
    return true;
}();


// ===== Property Reflection =====

BEGIN_PROPERTIES(AActor)
    ADD_PROPERTY(FName, ObjectName, "[액터]", true, "액터의 이름입니다")
    ADD_PROPERTY(FString, Tag, "[액터]", true, "액터의 태그를 지정합니다.")
    ADD_PROPERTY_METADATA(Tag, "LuaReadWrite", "true")
    ADD_PROPERTY(bool, bActorHiddenInGame, "[액터]", true)
    ADD_PROPERTY_METADATA(bActorHiddenInGame, "LuaReadWrite", "true")
    ADD_PROPERTY(bool, bActorIsActive, "[액터]", true)
    ADD_PROPERTY_METADATA(bActorIsActive, "LuaReadWrite", "true")
END_PROPERTIES()

// ===== Lua Binding =====

extern "C" void LuaBind_Anchor_AActor() {}

LUA_BIND_BEGIN(AActor)
{
    // No functions to bind
}
LUA_BIND_END()

