// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#include "pch.h"
#include "PrimitiveComponent.h"
#include "ObjectMacros.h"
#include "LuaBindHelpers.h"

// ===== Class Factory Registration (IMPLEMENT_CLASS) =====

// IMPLEMENT_CLASS(UPrimitiveComponent) expansion
namespace {
    struct UPrimitiveComponentFactoryRegister
    {
        UPrimitiveComponentFactoryRegister()
        {
            ObjectFactory::RegisterClassType(
                UPrimitiveComponent::StaticClass(),
                []() -> UObject* { return new UPrimitiveComponent(); }
            );
        }
    };
    static UPrimitiveComponentFactoryRegister GRegister_UPrimitiveComponent;
    static bool bIsRegistered_UPrimitiveComponent = [](){ UPrimitiveComponent::StaticClass(); return true; }();
}

// Static member initialization for reflection registration
const bool UPrimitiveComponent::bPropertiesRegistered = []() {
    UPrimitiveComponent::StaticRegisterProperties();
    return true;
}();


// ===== Property Reflection =====

BEGIN_PROPERTIES(UPrimitiveComponent)
    MARK_AS_COMPONENT("프리미티브 컴포넌트", "렌더링 가능한 기본 컴포넌트입니다")
    ADD_PROPERTY(bool, bGenerateOverlapEvents, "Shape", true)
    ADD_PROPERTY_METADATA(bGenerateOverlapEvents, "LuaReadWrite", "true")
    ADD_PROPERTY(bool, bBlockComponent, "Shape", true)
    ADD_PROPERTY_METADATA(bBlockComponent, "LuaReadWrite", "true")
END_PROPERTIES()

// ===== Lua Binding =====

extern "C" void LuaBind_Anchor_UPrimitiveComponent() {}

LUA_BIND_BEGIN(UPrimitiveComponent)
{
    // No functions to bind
}
LUA_BIND_END()

