// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#include "pch.h"
#include "SceneComponent.h"
#include "ObjectMacros.h"
#include "LuaBindHelpers.h"

// ===== Class Factory Registration (IMPLEMENT_CLASS) =====

// IMPLEMENT_CLASS(USceneComponent) expansion
namespace {
    struct USceneComponentFactoryRegister
    {
        USceneComponentFactoryRegister()
        {
            ObjectFactory::RegisterClassType(
                USceneComponent::StaticClass(),
                []() -> UObject* { return new USceneComponent(); }
            );
        }
    };
    static USceneComponentFactoryRegister GRegister_USceneComponent;
    static bool bIsRegistered_USceneComponent = [](){ USceneComponent::StaticClass(); return true; }();
}

// Static member initialization for reflection registration
const bool USceneComponent::bPropertiesRegistered = []() {
    USceneComponent::StaticRegisterProperties();
    return true;
}();


// ===== Property Reflection =====

BEGIN_PROPERTIES(USceneComponent)
    MARK_AS_COMPONENT("씬 컴포넌트", "트랜스폼을 가진 기본 컴포넌트입니다")
    ADD_PROPERTY(bool, bIsVisible, "렌더링", true)
    ADD_PROPERTY_METADATA(bIsVisible, "LuaReadWrite", "true")
    ADD_PROPERTY(FVector, RelativeLocation, "Transform", true)
    ADD_PROPERTY_METADATA(RelativeLocation, "LuaReadWrite", "true")
    ADD_PROPERTY(FVector, RelativeScale, "Transform", true)
    ADD_PROPERTY_METADATA(RelativeScale, "LuaReadWrite", "true")
    ADD_PROPERTY(FVector, RelativeRotationEuler, "Transform", true)
    ADD_PROPERTY_METADATA(RelativeRotationEuler, "LuaReadWrite", "true")
END_PROPERTIES()

// ===== Lua Binding =====

extern "C" void LuaBind_Anchor_USceneComponent() {}

LUA_BIND_BEGIN(USceneComponent)
{
    // No functions to bind
}
LUA_BIND_END()

