// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#include "pch.h"
#include "StaticMeshComponent.h"
#include "ObjectMacros.h"
#include "LuaBindHelpers.h"

// ===== Class Factory Registration (IMPLEMENT_CLASS) =====

// IMPLEMENT_CLASS(UStaticMeshComponent) expansion
namespace {
    struct UStaticMeshComponentFactoryRegister
    {
        UStaticMeshComponentFactoryRegister()
        {
            ObjectFactory::RegisterClassType(
                UStaticMeshComponent::StaticClass(),
                []() -> UObject* { return new UStaticMeshComponent(); }
            );
        }
    };
    static UStaticMeshComponentFactoryRegister GRegister_UStaticMeshComponent;
    static bool bIsRegistered_UStaticMeshComponent = [](){ UStaticMeshComponent::StaticClass(); return true; }();
}

// Static member initialization for reflection registration
const bool UStaticMeshComponent::bPropertiesRegistered = []() {
    UStaticMeshComponent::StaticRegisterProperties();
    return true;
}();


// ===== Property Reflection =====

BEGIN_PROPERTIES(UStaticMeshComponent)
    MARK_AS_COMPONENT("스태틱 메시 컴포넌트", "정적 메시를 렌더링하는 컴포넌트입니다")
    ADD_PROPERTY_STATICMESH(UStaticMesh*, StaticMesh, "Static Mesh", true, "Static mesh asset to render")
    ADD_PROPERTY_METADATA(StaticMesh, "LuaReadWrite", "true")
    ADD_PROPERTY_ARRAY(EPropertyType::Int32, TestIntArray, "Container Test", true, "Test integer array")
    ADD_PROPERTY_METADATA(TestIntArray, "LuaReadWrite", "true")
    ADD_PROPERTY_ARRAY(EPropertyType::Float, TestFloatArray, "Container Test", true, "Test float array")
    ADD_PROPERTY_METADATA(TestFloatArray, "LuaReadWrite", "true")
    ADD_PROPERTY_ARRAY(EPropertyType::FString, TestStringArray, "Container Test", true, "Test string array")
    ADD_PROPERTY_METADATA(TestStringArray, "LuaReadWrite", "true")
    ADD_PROPERTY_ARRAY(EPropertyType::FVector, TestVectorArray, "Container Test", true, "Test vector array")
    ADD_PROPERTY_METADATA(TestVectorArray, "LuaReadWrite", "true")
    ADD_PROPERTY_MAP(EPropertyType::FString, EPropertyType::Int32, TestStringIntMap, "Container Test", true, "Test string-to-int map")
    ADD_PROPERTY_METADATA(TestStringIntMap, "LuaReadWrite", "true")
    ADD_PROPERTY_MAP(EPropertyType::Int32, EPropertyType::Float, TestIntFloatMap, "Container Test", true, "Test int-to-float map")
    ADD_PROPERTY_METADATA(TestIntFloatMap, "LuaReadWrite", "true")
    ADD_PROPERTY_MAP(EPropertyType::FString, EPropertyType::FVector, TestStringVectorMap, "Container Test", true, "Test string-to-vector map")
    ADD_PROPERTY_METADATA(TestStringVectorMap, "LuaReadWrite", "true")
    ADD_PROPERTY_ARRAY(EPropertyType::Texture, TestTextureArray, "Container Test", true, "Test texture pointer array")
    ADD_PROPERTY_METADATA(TestTextureArray, "LuaReadWrite", "true")
    ADD_PROPERTY_ARRAY(EPropertyType::Material, TestMaterialArray, "Container Test", true, "Test material pointer array")
    ADD_PROPERTY_METADATA(TestMaterialArray, "LuaReadWrite", "true")
    ADD_PROPERTY_MAP(EPropertyType::FString, EPropertyType::Texture, TestStringTextureMap, "Container Test", true, "Test string-to-texture map")
    ADD_PROPERTY_METADATA(TestStringTextureMap, "LuaReadWrite", "true")
END_PROPERTIES()

// ===== Lua Binding =====

extern "C" void LuaBind_Anchor_UStaticMeshComponent() {}

LUA_BIND_BEGIN(UStaticMeshComponent)
{
    // No functions to bind
}
LUA_BIND_END()

