#!/usr/bin/env python3
"""
Mundi Engine - Lua 바인딩 자동 생성 도구

UPROPERTY와 UFUNCTION 매크로를 파싱하여
.generated.cpp 파일을 자동 생성합니다.

사용법:
    python generate.py --source-dir <소스 디렉토리> --output-dir <출력 디렉토리>
"""

import argparse
import sys
import os
from pathlib import Path
import subprocess

# Add current script directory to Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from header_parser import HeaderParser
from property_generator import PropertyGenerator
from lua_generator import LuaBindingGenerator
from vcxproj_parser import VcxprojParser


GENERATED_HEADER_TEMPLATE = """// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#pragma once

// Macro expansion for GENERATED_REFLECTION_BODY()
// This file must be included BEFORE the class definition
#ifdef CURRENT_CLASS_GENERATED_BODY
#undef CURRENT_CLASS_GENERATED_BODY
#endif
#define CURRENT_CLASS_GENERATED_BODY \\
public: \\
    using Super = {parent_class}; \\
    using ThisClass_t = {class_name}; \\
    static UClass* StaticClass() \\
    {{ \\
        static UClass Cls{{ "{class_name}", {parent_class}::StaticClass(), sizeof({class_name}) }}; \\
        static bool bRegistered = (UClass::SignUpClass(&Cls), true); \\
        return &Cls; \\
    }} \\
    virtual UClass* GetClass() const override {{ return {class_name}::StaticClass(); }} \\
    {class_name}(const {class_name}&) = default; \\
    {duplicate_method} \\
private: \\
    static void StaticRegisterProperties(); \\
    static const bool bPropertiesRegistered; \\
public:
"""

DUPLICATE_METHOD_CONCRETE = """{class_name}* Duplicate() const override \\
    {{ \\
        {class_name}* NewObject = ObjectFactory::DuplicateObject<{class_name}>(this); \\
        NewObject->DuplicateSubObjects(); \\
        NewObject->PostDuplicate(); \\
        return NewObject; \\
    }}"""

DUPLICATE_METHOD_ABSTRACT = """{class_name}* Duplicate() const override \\
    {{ \\
        assert(false && "Cannot duplicate abstract class {class_name}"); \\
        return nullptr; \\
    }}"""

GENERATED_STRUCT_HEADER_TEMPLATE = """// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#pragma once

// Macro expansion for GENERATED_REFLECTION_BODY()
// This file must be included BEFORE the struct definition
#ifdef CURRENT_CLASS_GENERATED_BODY
#undef CURRENT_CLASS_GENERATED_BODY
#endif
#define CURRENT_CLASS_GENERATED_BODY \\
public: \\
    using ThisClass_t = {struct_name}; \\
    static UStruct* StaticStruct() \\
    {{ \\
        static UStruct Str{{ "{struct_name}", sizeof({struct_name}) }}; \\
        static bool bRegistered = (UStruct::SignUpStruct(&Str), true); \\
        return &Str; \\
    }} \\
private: \\
    static void StaticRegisterProperties(); \\
    static const bool bPropertiesRegistered; \\
public:
"""

GENERATED_CPP_TEMPLATE = """// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#include "pch.h"
#include "{header_include}"
#include "{object_macros_include}"
#include "{lua_helpers_include}"

// ===== Class Factory Registration (IMPLEMENT_CLASS) =====
{implement_class_code}

// ===== Property Reflection =====
{property_code}

// ===== Lua Binding =====
{lua_code}
"""


def write_file_if_different(file_path: Path, new_content: str) -> bool:
    """
    파일 내용이 실제로 다를 때만 파일을 씁니다.
    타임스탬프를 유지하여 불필요한 재컴파일을 방지합니다.

    Returns:
        True if file was written, False if content was identical
    """
    # 파일이 이미 존재하고 내용이 같으면 건너뛰기
    if file_path.exists():
        existing_content = file_path.read_text(encoding='utf-8')
        if existing_content == new_content:
            return False

    # 내용이 다르거나 파일이 없으면 쓰기
    file_path.write_text(new_content, encoding='utf-8')
    return True


def generate_header_file(class_info):
    """.generated.h 파일 생성"""
    # Enum 메타데이터 생성
    enum_metadata = ""
    if hasattr(class_info, 'enums') and class_info.enums:
        for enum_info in class_info.enums:
            enum_metadata += f"\n// Enum: {enum_info.name}\n"
            enum_metadata += f"namespace {enum_info.name}_Meta {{\n"
            enum_metadata += f"    inline const char* ToString({enum_info.name} Value) {{\n"
            enum_metadata += "        switch(Value) {\n"
            for name, value in enum_info.values.items():
                enum_metadata += f"            case {enum_info.name}::{name}: return \"{name}\";\n"
            enum_metadata += f"            default: return \"Unknown\";\n"
            enum_metadata += "        }\n"
            enum_metadata += "    }\n"
            enum_metadata += f"    inline {enum_info.name} FromString(const char* Str) {{\n"
            for name, value in enum_info.values.items():
                enum_metadata += f"        if (strcmp(Str, \"{name}\") == 0) return {enum_info.name}::{name};\n"
            # 첫 번째 값을 기본값으로
            first_name = list(enum_info.values.keys())[0] if enum_info.values else "None"
            enum_metadata += f"        return {enum_info.name}::{first_name}; // default\n"
            enum_metadata += "    }\n"

            # Enum 값 목록 배열 생성
            enum_metadata += f"    inline const char* const* GetAllValueNames() {{\n"
            enum_metadata += f"        static const char* values[] = {{\n"
            for name in enum_info.values.keys():
                enum_metadata += f"            \"{name}\",\n"
            enum_metadata += f"            nullptr\n"
            enum_metadata += f"        }};\n"
            enum_metadata += f"        return values;\n"
            enum_metadata += "    }\n"

            # Enum 값 개수
            enum_count = len(enum_info.values)
            enum_metadata += f"    inline int GetValueCount() {{\n"
            enum_metadata += f"        return {enum_count};\n"
            enum_metadata += "    }\n"

            # int 기반 ToString (Registry에서 사용)
            enum_metadata += f"    inline const char* ToStringFromInt(int Value) {{\n"
            enum_metadata += f"        return ToString(static_cast<{enum_info.name}>(Value));\n"
            enum_metadata += "    }\n"

            # int 기반 FromString (Registry에서 사용)
            enum_metadata += f"    inline int FromStringToInt(const char* Str) {{\n"
            enum_metadata += f"        return static_cast<int>(FromString(Str));\n"
            enum_metadata += "    }\n"

            enum_metadata += "}\n"

    # enum_only인 경우: enum 메타데이터만 반환 (GENERATED_BODY 매크로 없음)
    if hasattr(class_info, 'type') and class_info.type == "enum_only":
        header = "// Auto-generated file - DO NOT EDIT!\n"
        header += "// Generated by Tools/CodeGenerator/generate.py\n\n"
        header += "#pragma once\n"
        return enum_metadata + header

    # struct인 경우 별도 템플릿 사용
    if hasattr(class_info, 'type') and class_info.type == "struct":
        header = GENERATED_STRUCT_HEADER_TEMPLATE.format(
            struct_name=class_info.name
        )
        return enum_metadata + header

    # class인 경우 기존 로직
    # 추상 클래스는 순수 가상 Duplicate(), 일반 클래스는 구체적 구현
    if class_info.is_abstract:
        duplicate_method = DUPLICATE_METHOD_ABSTRACT.format(class_name=class_info.name)
    else:
        duplicate_method = DUPLICATE_METHOD_CONCRETE.format(class_name=class_info.name)

    header = GENERATED_HEADER_TEMPLATE.format(
        class_name=class_info.name,
        parent_class=class_info.parent,
        duplicate_method=duplicate_method
    )
    return enum_metadata + header


def generate_implement_class(class_info):
    """IMPLEMENT_CLASS 매크로 확장 코드 생성 (class) / 프로퍼티 등록 코드 생성 (struct)"""
    class_name = class_info.name

    # struct인 경우 팩토리 등록 없이 프로퍼티만 등록
    if hasattr(class_info, 'type') and class_info.type == "struct":
        return f"""
// Static member initialization for reflection registration
const bool {class_name}::bPropertiesRegistered = []() {{
    {class_name}::StaticRegisterProperties();
    return true;
}}();
"""

    # class인 경우 기존 로직 (팩토리 등록 + 프로퍼티 등록)
    # 추상 클래스는 팩토리 함수를 nullptr로 등록
    if class_info.is_abstract:
        factory_lambda = "nullptr"
    else:
        factory_lambda = f"[]() -> UObject* {{ return new {class_name}(); }}"

    return f"""
// IMPLEMENT_CLASS({class_name}) expansion
namespace {{
    struct {class_name}FactoryRegister
    {{
        {class_name}FactoryRegister()
        {{
            ObjectFactory::RegisterClassType(
                {class_name}::StaticClass(),
                {factory_lambda}
            );
        }}
    }};
    static {class_name}FactoryRegister GRegister_{class_name};
    static bool bIsRegistered_{class_name} = [](){{ {class_name}::StaticClass(); return true; }}();
}}

// Static member initialization for reflection registration
const bool {class_name}::bPropertiesRegistered = []() {{
    {class_name}::StaticRegisterProperties();
    return true;
}}();
"""


def generate_cpp_file(class_info, prop_gen, lua_gen, vcxproj_parser: VcxprojParser = None):
    """.generated.cpp 파일 생성"""
    # enum_only인 경우: cpp 파일 불필요 (enum은 헤더에만 존재)
    if hasattr(class_info, 'type') and class_info.type == "enum_only":
        return None

    # vcxproj_parser가 있으면 사용, 없으면 기본 동작
    if vcxproj_parser:
        # 헤더 파일을 프로젝트 루트 기준 절대 경로로 변환
        header_include = vcxproj_parser.get_project_relative_path(class_info.header_file)

        # ObjectMacros.h를 VS처럼 resolve하여 절대 경로로 변환
        object_macros_include = vcxproj_parser.convert_to_absolute_include("ObjectMacros.h")

        # LuaBindHelpers.h를 VS처럼 resolve하여 절대 경로로 변환
        lua_helpers_include = vcxproj_parser.convert_to_absolute_include("LuaBindHelpers.h")
    else:
        # vcxproj_parser 없으면 파일명만 사용 (fallback)
        header_include = class_info.header_file.name
        object_macros_include = "ObjectMacros.h"
        lua_helpers_include = "LuaBindHelpers.h"

    # IMPLEMENT_CLASS 코드 생성
    implement_class_code = generate_implement_class(class_info)

    # 프로퍼티 코드 생성
    property_code = prop_gen.generate(class_info)

    # Lua 바인딩 코드 생성 (struct는 생략)
    if hasattr(class_info, 'type') and class_info.type == "struct":
        lua_code = "// Struct - No Lua binding needed"
    else:
        lua_code = lua_gen.generate(class_info)

    # 최종 파일 내용
    return GENERATED_CPP_TEMPLATE.format(
        header_include=header_include,
        object_macros_include=object_macros_include,
        lua_helpers_include=lua_helpers_include,
        implement_class_code=implement_class_code,
        property_code=property_code,
        lua_code=lua_code
    )


def generate_enum_registry_header(all_enums):
    """Enum Registry 헤더 파일 생성"""
    code = """// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#pragma once

namespace EnumRegistry {

// Enum 메타데이터 구조체
struct FEnumMeta {
    const char* TypeName;
    const char* const* (*GetAllValueNames)();
    int (*GetValueCount)();
    const char* (*ToStringFromInt)(int Value);  // int 기반 ToString
    int (*FromStringToInt)(const char* Str);    // int 기반 FromString
};

// 타입 이름으로 Enum 메타데이터 조회
const FEnumMeta* GetEnumMeta(const char* typeName);

}  // namespace EnumRegistry
"""
    return code


def generate_enum_registry_cpp(all_enums):
    """Enum Registry cpp 파일 생성"""

    # 필요한 헤더들 include
    includes = set()
    for enum_info in all_enums:
        # enum이 정의된 헤더 파일의 generated 헤더 include
        # 예: AnimationTypes.h -> AnimationTypes.generated.h
        includes.add(f"#include \"{enum_info.header_file.stem}.generated.h\"")

    includes_code = "\n".join(sorted(includes))

    # Registry 엔트리 생성
    registry_entries = []
    for enum_info in all_enums:
        entry = f"""    {{
        "{enum_info.name}",
        &{enum_info.name}_Meta::GetAllValueNames,
        &{enum_info.name}_Meta::GetValueCount,
        &{enum_info.name}_Meta::ToStringFromInt,
        &{enum_info.name}_Meta::FromStringToInt
    }}"""
        registry_entries.append(entry)

    registry_entries_code = ",\n".join(registry_entries)

    code = f"""// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#include "pch.h"
#include "EnumRegistry.generated.h"
{includes_code}

#include <unordered_map>
#include <string>

namespace EnumRegistry {{

// 전역 Registry
static const FEnumMeta g_EnumRegistry[] = {{
{registry_entries_code}
}};

static constexpr int g_EnumCount = {len(all_enums)};

const FEnumMeta* GetEnumMeta(const char* typeName) {{
    if (!typeName) return nullptr;

    for (int i = 0; i < g_EnumCount; ++i) {{
        if (strcmp(g_EnumRegistry[i].TypeName, typeName) == 0) {{
            return &g_EnumRegistry[i];
        }}
    }}

    return nullptr;
}}

}}  // namespace EnumRegistry
"""
    return code


def main():
    parser = argparse.ArgumentParser(
        description='Mundi Engine Lua Binding Auto-Generator'
    )
    parser.add_argument(
        '--source-dir',
        type=Path,
        required=True,
        help='소스 디렉토리 경로 (예: Source/Runtime)'
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        required=True,
        help='생성된 파일 출력 디렉토리 (예: Build/Generated)'
    )
    parser.add_argument(
        '--vcxproj',
        type=Path,
        default=None,
        help='업데이트할 .vcxproj 파일 경로 (예: Mundi.vcxproj)'
    )

    args = parser.parse_args()

    # 디렉토리 존재 확인
    if not args.source_dir.exists():
        print(f"[ERROR] Source directory not found: {args.source_dir}")
        sys.exit(1)

    # 출력 디렉토리 생성
    args.output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print(" Mundi Engine - Code Generator")
    print("=" * 60)
    print(f" Source: {args.source_dir}")
    print(f" Output: {args.output_dir}")

    # vcxproj 파서 초기화 (include 경로 자동 해석용)
    vcxproj_parser = None
    if args.vcxproj and args.vcxproj.exists():
        print(f" Vcxproj: {args.vcxproj}")
        vcxproj_parser = VcxprojParser(args.vcxproj)
        print(f" Include Dirs: {len(vcxproj_parser.include_dirs)} directories parsed")
    else:
        print(f" Vcxproj: Not specified (using fallback include paths)")
    print()

    # 파서 초기화
    header_parser = HeaderParser()
    prop_gen = PropertyGenerator()
    lua_gen = LuaBindingGenerator()

    # 헤더 파일 스캔
    print(" Scanning for reflection classes...")
    classes = header_parser.find_reflection_classes(args.source_dir)

    if not classes:
        print("[WARNING] No classes with GENERATED_REFLECTION_BODY() or UENUM() found.")
        return

    print(f"\n Found {len(classes)} reflection class(es)\n")

    # 각 클래스에 대해 .generated.h와 .generated.cpp 생성
    generated_files = []
    updated_count = 0
    skipped_count = 0

    for class_info in classes:
        # .generated.h 파일 생성
        header_output = args.output_dir / f"{class_info.name}.generated.h"
        header_code = generate_header_file(class_info)
        header_updated = write_file_if_different(header_output, header_code)
        if header_updated:
            updated_count += 1
        generated_files.append(header_output)

        # .generated.cpp 파일 생성 (enum_only는 제외)
        cpp_updated = False
        cpp_output = None
        cpp_code = generate_cpp_file(class_info, prop_gen, lua_gen, vcxproj_parser)
        if cpp_code is not None:
            cpp_output = args.output_dir / f"{class_info.name}.generated.cpp"
            cpp_updated = write_file_if_different(cpp_output, cpp_code)
            if cpp_updated:
                updated_count += 1
            generated_files.append(cpp_output)

        # 상태 표시
        if header_updated or cpp_updated:
            status = " Updated"
        else:
            status = "  Skipped (no changes)"
            skipped_count += 1

        print(f"{status}: {class_info.name}")
        if header_updated:
            print(f"  |- {header_output.name} (modified)")
        if cpp_updated and cpp_output:
            print(f"  |- {cpp_output.name} (modified)")

        # enum_only인 경우 enum 개수만 표시
        if hasattr(class_info, 'type') and class_info.type == "enum_only":
            print(f"  \\- Enums: {len(class_info.enums)}")
        else:
            print(f"  |- Properties: {len(class_info.properties)}")
            print(f"  \\- Functions:  {len([f for f in class_info.functions if f.metadata.get('lua_bind')])}")

    # Enum Registry 생성
    print("\n" + "=" * 60)
    print(" Generating Enum Registry...")
    print("=" * 60)

    all_enums = []
    for class_info in classes:
        if hasattr(class_info, 'enums') and class_info.enums:
            all_enums.extend(class_info.enums)

    if all_enums:
        registry_header = generate_enum_registry_header(all_enums)
        registry_cpp = generate_enum_registry_cpp(all_enums)

        registry_header_path = args.output_dir / "EnumRegistry.generated.h"
        registry_cpp_path = args.output_dir / "EnumRegistry.generated.cpp"

        registry_header_updated = write_file_if_different(registry_header_path, registry_header)
        registry_cpp_updated = write_file_if_different(registry_cpp_path, registry_cpp)

        if registry_header_updated or registry_cpp_updated:
            updated_count += 1

        generated_files.append(registry_header_path)
        generated_files.append(registry_cpp_path)

        print(f" Registered {len(all_enums)} enum type(s)")
        if registry_header_updated:
            print(f"  |- EnumRegistry.generated.h (modified)")
        if registry_cpp_updated:
            print(f"  |- EnumRegistry.generated.cpp (modified)")
    else:
        print(" No enums found, skipping registry generation")

    print()
    print("=" * 60)
    print(f" Code generation complete!")
    print(f"   Total files: {len(generated_files)}")
    print(f"   Updated: {updated_count}")
    print(f"   Skipped: {skipped_count * 2} (unchanged)")
    print("=" * 60)

    # vcxproj 업데이트
    if args.vcxproj and args.vcxproj.exists():
        print()
        print("=" * 60)
        print(" Updating Visual Studio Project...")
        print("=" * 60)

        # vcxproj_updater.py 실행
        updater_script = Path(__file__).parent / "vcxproj_updater.py"
        if updater_script.exists():
            cmd = [sys.executable, str(updater_script), str(args.vcxproj)] + [str(f) for f in generated_files]
            try:
                result = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8')
                print(result.stdout)
                if result.returncode != 0:
                    print(f"[WARNING] vcxproj update failed: {result.stderr}")
            except Exception as e:
                print(f"[WARNING] Failed to run vcxproj updater: {e}")
        else:
            print(f"[WARNING] vcxproj_updater.py not found at {updater_script}")
    elif args.vcxproj:
        print(f"\n[WARNING] vcxproj file not found: {args.vcxproj}")


if __name__ == '__main__':
    main()
